### ISSUE TITLE
vagrant rsync-auto issue!

### ISSUE THREAD

**Issue by mrehanali** [nmb007/vagrant-lamp#4]
## Following error occurred when executed the 'vagrant rsync-auto' command

==> default: Doing an initial rsync...
==> default: Rsyncing folder: /home/coeus/projects/lidl/ => /var/www/lidl
==> default:   - Exclude: [".vagrant/", ".git/"]
==> default: Watching: /home/coeus/projects/lidl
/opt/vagrant/embedded/gems/gems/listen-3.0.2/lib/listen/event/queue.rb:15: warning: toplevel constant Queue referenced by Thread::Queue
/opt/vagrant/embedded/gems/gems/listen-3.0.2/lib/listen/event/loop.rb:16: warning: toplevel constant Queue referenced by Thread::Queue
FATAL: Listen error: unable to monitor directories for changes.
Visit https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers for info on how to fix this.

**Comment by nmb007** [comment]
Follow this link https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers to increase the limit and it should fix this error
